version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      salesforce:
        patterns:
          - "@salesforce/*"
          - "jsforce"
    ignore:
      - dependency-type: "development"
    reviewers:
      - "noriabits"
