window.MonitoringLabels = {
  pillAll: 'All',
  btnAddChart: '+ Add Chart',
  btnEdit: 'Edit',
  btnRefresh: 'Refresh',
  btnPreview: 'Preview',
  btnSave: 'Save',
  btnCancel: 'Cancel',
  btnAddValueField: '+ Add field',
  btnRemoveValueField: '−',
  statusLoading: 'Loading...',
  statusNoData: 'No data returned.',
  statusRows: (n) => `${n} row${n === 1 ? '' : 's'}`,
  noResults: 'No matching charts found.',
  noConfigs:
    'No monitoring configs found. Add YAML files to force-cockpit/monitoring/ or click "+ Add Chart".',
  errorNotConnected: 'Connect to an org to load charts.',
  labelName: 'Name',
  labelDescription: 'Description',
  labelCategory: 'Category',
  labelSoql: 'SOQL Query',
  labelLabelField: 'Label field',
  labelValueFields: 'Value fields',
  labelValueFieldApi: 'API name',
  labelValueFieldLabel: 'Display label',
  labelValueFieldFormat: 'Format',
  labelChartType: 'Chart type',
  labelStacked: 'Stacked bars',
  labelRefreshInterval: 'Auto-refresh (seconds, 0 = off)',
  placeholderName: 'My Chart',
  placeholderDescription: 'What this chart shows...',
  placeholderCategory: 'general',
  placeholderSoql: 'SELECT Field, COUNT(Id) Cnt FROM Object__c GROUP BY Field',
  placeholderLabelField: 'Field',
  placeholderValueFieldApi: 'Cnt',
  placeholderValueFieldLabel: 'Count',
  chartTypes: {
    bar: 'Bar',
    line: 'Line',
    pie: 'Pie',
    doughnut: 'Doughnut',
    metric: 'Metric (KPI)',
    table: 'Table',
  },
  formatOptions: { '': 'None', currency: 'Currency', percent: 'Percent' },
  placeholderThreshold: 'Threshold',
  labelThresholdCondition: 'Condition',
  conditionOptions: { above: '≥ Above', below: '≤ Below' },
  // Private
  labelPrivate: 'Private (not committed to git)',
  badgePrivate: '🔒',
  filterAll: 'All',
  filterShared: 'Shared',
  filterPrivate: 'Private',
  pillSubAll: 'All',
  errorDuplicateId: 'A config with the same category and name already exists in the other folder.',
};
