// @ts-nocheck
window.YamlScriptsLabels = {
  pillAll: 'All',
  btnExecute: 'Execute',
  statusExecuting: 'Executing...',
  noResults: 'No matching scripts found.',
  noScripts: 'No scripts found in force-cockpit/scripts folder.',
  errorNotConnected: 'Connect to an org to execute scripts.',
  checkboxUserDebugOnly: 'Show only USER_DEBUG lines',
  checkboxPrettyJson: 'Format JSON',
  badgeApex: 'Apex',
  badgeCommand: 'Command',
  badgeJs: 'JS',
  badgeInvalid: '⚠ Invalid',
  tooltipInvalidScript: 'Fix the YAML file to execute this script',
  btnNewScript: '+ New',
  btnSave: 'Save',
  btnCancel: 'Cancel',
  labelName: 'Name',
  labelDescription: 'Description',
  labelType: 'Type',
  labelFolder: 'Category',
  labelContent: 'Content',
  placeholderName: 'My Script',
  placeholderDescription: 'What this script does...',
  placeholderFolder: 'Choose category...',
  errorFolderRequired: 'Category is required.',
  placeholderApexContent: "System.debug('hello');",
  placeholderCommandContent: 'npm run build',
  placeholderJsContent:
    'const result = await query("SELECT Id, Name FROM Account LIMIT 5");\nlog(JSON.stringify(result.records, null, 2));',
  typeApex: 'Apex',
  typeCommand: 'Command',
  typeJs: 'JavaScript',
  errorNameRequired: 'Name is required.',
  errorContentRequired: 'Content is required.',
  btnEdit: '✏',
  btnDelete: 'Delete',
  tooltipEditScript: 'Edit script',
  // Inputs
  labelInputs: 'Inputs',
  btnAddInput: '+ Add Input',
  placeholderInputName: 'variableName',
  placeholderInputLabel: 'Display label (defaults to name)',
  labelRequired: 'Required',
  btnRemoveInput: '×',
  labelInputType: 'Type',
  typeString: 'String',
  typePicklist: 'Picklist',
  typeCheckbox: 'Checkbox',
  typeTextarea: 'Textarea',
  labelCheckboxDefault: 'Checked by default',
  placeholderOptions: 'Option1, Option2, Option3',
  errorInputNameInvalid:
    'Input names must be alphanumeric (a-z, 0-9, _) and start with a letter or underscore.',
  errorInputNameDuplicate: 'Duplicate input name found.',
  errorPicklistOptionsRequired: 'Picklist inputs require at least one option.',
  // Private
  labelPrivate: 'Private (not committed to git)',
  badgePrivate: '🔒',
  filterAll: 'All',
  filterFavorites: '⭐Favorites',
  filterShared: 'Shared',
  filterPrivate: 'Private',
  favorite: 'Add to favorites',
  unfavorite: 'Remove from favorites',
  pillSubAll: 'All',
  errorDuplicateId: 'A script with the same category and name already exists in the other folder.',
  // Source / file-based scripts
  labelSource: 'Source',
  sourceInline: 'Inline code',
  sourceFile: 'From file',
  labelFilePath: 'File path',
  placeholderFilePath: 'path/to/script.cls (relative to workspace)',
  btnBrowse: '📁 Browse',
  errorFilePathRequired: 'File path is required.',
};
